#!/usr/bin/python3
def raise_exceptions():
    a = 'foo'
    b = 4
    c = a + b
